# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4db47b4c5ed3989c5f11e0d7f3b8eafeda4cff99998e939f867dfe2a7c6409fe2e66da7ce8833df3aacc7c2672fae45ede4c0ffb8a0bf6bcf3729fa5bb47ff66

test:
  secret_key_base: 9c7c77368d3755f86545a9b901a406f118150f6752814b795b428dc8cd01b6966fc15237b0d9806758b0170e9537520bb4bf8fcc1897d1cff6f33c7e2b4bfb13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
